update Docker entrypoint script for AWS

diff --git a/django-app/compose/production/django/entrypoint b/django-app/compose/production/django/entrypoint
--- a/django-app/compose/production/django/entrypoint
+++ b/django-app/compose/production/django/entrypoint
@@ -1,11 +1,12 @@
-#!/bin/bash
+#!/bin/sh
 
 set -o errexit
 set -o pipefail
 set -o nounset
 
 
-
+# N.B. If only .env files supported variable expansion...
+export CELERY_BROKER_URL="${REDIS_URL}"
 
 if [ -z "${POSTGRES_USER}" ]; then
     base_postgres_image_default_user='postgres'
@@ -37,6 +38,8 @@ until postgres_ready; do
   >&2 echo 'Waiting for PostgreSQL to become available...'
   sleep 1
 done
->&2 echo 'PostgreSQL is available'
+>&2 echo 'PostgreSQL is available. Super!'
 
-exec "$@"
+python /app/manage.py collectstatic --noinput
+python /app/manage.py migrate
+/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:8000 --chdir=/app  --access-logfile '-' --error-logfile '-' --capture-output
